Repository m3ntorship/pickly-frontend, pull requests merged in 2020-10, with the labels that each got.

#17 Reusable Heading Component
  src/components/Heading/Heading.stories.js
  src/components/Heading/index.js
  tailwind.config.js
Labels: Request changes

#23 Feature/uploading progress
  src/App.js
  src/components/Uploading-progress/index.js
  src/components/Uploading-progress/uploadingProgress.stories.js
Labels: Ready for review

#22 Creating ImageWithSideTitle
  src/components/ImageWithSideTitle/ImageWithSideTitle.stories.js
  src/components/ImageWithSideTitle/index.jsx
Labels: Approved

#26 Feature/share button
  package.json
  src/components/ShareBtn/ShareBtn.stories.js
  src/components/ShareBtn/index.js
  yarn.lock
Labels: Ready for review

#27 Feature/toggle option button
  src/components/ToggleButton/ToggleButton.stories.js
  src/components/ToggleButton/index.js
  src/components/Uploading-progress/index.js
  src/style/global.css
  tailwind.config.js
Labels: Approved

#20 Feature/reusable button
  src/components/Button/Button.stories.js
  src/components/Button/index.js
  tailwind.config.js
Labels: Ready for review

#33 Feature/input field
  src/components/InputField/index.js
  src/components/InputField/inputField.stories.js
Labels: Ready for review

#36 Feature/login form
  package.json
  src/App.js
  src/components/LoginForm/backgrounds/background1.png
  src/components/LoginForm/backgrounds/background2.png
  src/components/LoginForm/fire.js
  src/components/LoginForm/index.js
  src/components/LoginForm/loginForm.stories.js
  src/context/userContext.js
  src/style/tailwind.css
  tailwind.config.js
  yarn.lock
Labels: Ready for review

#35 Navbar Section
  package.json
  src/App.js
  src/components/LoginForm/index.js
  src/components/Navbar-icons/index.js
  src/components/NavbarSection/index.jsx
  src/components/NavbarSection/navbar.stories.js
  src/pages/friends.jsx
  src/pages/home.jsx
  src/pages/notifications.jsx
  src/pages/profile.jsx
  src/style/global.css
  tailwind.config.js
  yarn.lock
Labels: Ready for review

#42 Creating Post Section
  .vscode/settings.json
  src/App.js
  src/components/ImageWithSideTitle/index.jsx
  src/components/PostSection/PostSection.stories.js
  src/components/PostSection/index.jsx
  src/components/ShareBtn/index.js
  src/pages/home.jsx
Labels: Approved

#44 Handle Post Image and get Posts
  src/components/Button/index.js
  src/components/LoginForm/index.js
  src/components/OptionsBtn/index.js
  src/components/PostSection/index.jsx
  src/components/ShareBtn/index.js
  src/components/UploadSection/index.js
  src/context/userContext.js
  src/pages/friends.jsx
  src/pages/home.jsx
  src/pages/notifications.jsx
  src/pages/profile.jsx
Labels: Ready for review

#57 adding random content
  src/pages/friends.jsx
  src/pages/notifications.jsx
  src/pages/profile.jsx
Labels: Ready for review

#64 Created the upload page & route
  src/App.js
  src/components/PostSomething/MultipleImagesBtn.js
  src/components/PostSomething/OneImageBtn.js
  src/pages/post.jsx
Labels: Ready for review

#67 Create Post Button
  src/components/CreatePostButon/index.jsx
  src/pages/home.jsx
Labels: Approved

#61 use custom axios in home.jsx
  src/pages/home.jsx
Labels: Approved

#71 optimize background-Image for login page
  src/components/LoginForm/backgrounds/background1.png
  src/components/LoginForm/backgrounds/background2.png
  src/components/LoginForm/backgrounds/background_Loginpage.webp
  src/components/LoginForm/index.js
Labels: Approved

#72 Heart icon button
  src/components/NavbarSection/index.jsx
  src/components/PostSection/HeartIcon/HeartIcon.stories.js
  src/components/PostSection/HeartIcon/index.js
  src/components/PostSection/index.jsx
Labels: Approved

#76 Feature / handle voting
  src/components/PostSection/PostSection.stories.js
  src/components/PostSection/index.jsx
  src/components/UploadSection/index.js
  src/pages/home.jsx
Labels: Ready for review

#69 Handle the Upload & Crop
  package.json
  public/manifest.json
  src/apis/clients/pickly/index.js
  src/components/InputField/index.js
  src/components/PostSection/index.jsx
  src/components/UploadSection/OneImage.js
  src/components/UploadSection/cropImage.js
  src/components/UploadSection/image.stories.js
  src/components/UploadSection/index.js
  src/components/UploadSection/uploadSection.stories.js
  src/configs/index.js
  src/pages/home.jsx
  src/style/tailwind.css
  tailwind.config.js
  yarn.lock
Labels: Ready for review

#84 adding post icon to navbar & ramove friends route and icon
  src/App.js
  src/components/NavbarSection/index.jsx
  src/components/NavbarSection/post-icon.svg
Labels: Approved

#88 Created Notifiction UI
  src/components/Notifications/Notifications.stories.js
  src/components/Notifications/index.js
  src/pages/notifications.jsx
  src/pages/post.jsx
Labels: Approved

#95 Fixupload section & login form stories
  src/App.js
  src/components/LoginForm/index.js
  src/components/LoginForm/loginForm.stories.js
  src/components/UploadSection/index.js
  src/components/UploadSection/uploadSection.stories.js
  src/pages/login.jsx
  src/pages/post.jsx
Labels: Approved

#91 create single post route
  src/App.js
  src/components/ImageWithSideTitle/index.jsx
  src/components/OptionsBtn/index.js
  src/components/PostSection/HeartIcon/index.js
  src/components/PostSection/PostSection.stories.js
  src/components/PostSection/index.jsx
  src/components/ShareBtn/index.js
  src/pages/home.jsx
  src/pages/singlePost.jsx
Labels: Ready for review

#99 handling voted image
  src/components/PostSection/HeartIcon/HeartIcon.stories.js
  src/components/PostSection/HeartIcon/index.js
  src/components/PostSection/PostSection.stories.js
  src/components/PostSection/index.jsx
  tailwind.config.js
Labels: Approved

#108 fix upload route styles
  src/components/InputField/index.js
  src/components/UploadSection/OneImage.js
  src/components/UploadSection/index.js
  src/pages/home.jsx
  src/pages/post.jsx
Labels: Ready for review
